<?php

$_COS_LANG_MODULE = array ();

$_COS_LANG_MODULE['flood: You should be able to post'] = 'Du kan post igen';
$_COS_LANG_MODULE['flood: You can post agian'] = 'Blot vend tilbage og post igen';

$_COS_LANG_MODULE['flood:: exceed time limit title'] = 'Du kan ikke poste i øjeblikket';
$_COS_LANG_MODULE['flood: Max Amount of posts is'] = 'Max post er ';
$_COS_LANG_MODULE['flood: per'] = ' per ';

$_COS_LANG_MODULE['flood: Your post counter will be reset in'] = 'Du kan poste igen om  ';
$_COS_LANG_MODULE['flood: minutes and'] = ' minut(er) og ';
$_COS_LANG_MODULE['flood: seconds'] = ' sekund(er) ';



$_COS_LANG_MODULE['flood: days and'] = ' dag(e)  og ';
$_COS_LANG_MODULE['flood: hours and'] = ' time(r) og ';
