<?php

$_COS_LANG_MODULE['flood: You can post agian'] = '只是继续前进，又使文章';
$_COS_LANG_MODULE['flood: You should be able to post'] = '你应该能够发布';
$_COS_LANG_MODULE['flood:: exceed time limit title'] = '不可以张贴，现在';
$_COS_LANG_MODULE['flood: Max Amount of posts is'] = '帖子的最大金额';
$_COS_LANG_MODULE['flood: per'] = '每';
$_COS_LANG_MODULE['flood: days and'] = '天与';
$_COS_LANG_MODULE['flood: hours and'] = '小时（S）和';
$_COS_LANG_MODULE['flood: minutes and'] = '分钟和';
$_COS_LANG_MODULE['flood: seconds'] = '秒';
$_COS_LANG_MODULE['flood: Your post counter will be reset in'] = '您的帖子计数器将被重置';
