<?php


// Translation of file /modules/flood/module.php

$_COS_LANG_MODULE['flood: You can post agian'] = 'Just go ahead and makes posts again';
$_COS_LANG_MODULE['flood: You should be able to post'] = 'You should be able to post';
$_COS_LANG_MODULE['flood:: exceed time limit title'] = 'Not possible to post right now';
$_COS_LANG_MODULE['flood: Max Amount of posts is'] = 'Max Amount of posts is ';
$_COS_LANG_MODULE['flood: per'] = ' per ';
$_COS_LANG_MODULE['flood: days and'] = ' day(s) and ';
$_COS_LANG_MODULE['flood: hours and'] = ' hour(s) and ';
$_COS_LANG_MODULE['flood: minutes and'] = ' minute(s) and ';
$_COS_LANG_MODULE['flood: seconds'] = ' second(s)';
$_COS_LANG_MODULE['flood: Your post counter will be reset in'] = 'Your post counter will be reset in ';
