<?php

$_COS_LANG_MODULE['flood: You should be able to post'] = 'Du kan legge igjen';
$_COS_LANG_MODULE['flood: You can post agian'] = 'Bare gå tilbake og legge igjen';
$_COS_LANG_MODULE['flood:: exceed time limit title'] = 'Du kan ikke starte i dag';
$_COS_LANG_MODULE['flood: Max Amount of posts is'] = 'Max posten er';
$_COS_LANG_MODULE['flood: per'] = 'per';
$_COS_LANG_MODULE['flood: Your post counter will be reset in'] = 'Du kan legge igjen';
$_COS_LANG_MODULE['flood: minutes and'] = 'minutt (er) og';
$_COS_LANG_MODULE['flood: seconds'] = 'sekund (s)';
$_COS_LANG_MODULE['flood: hours and'] = 'time (r) og';
$_COS_LANG_MODULE['flood: days and'] = 'dag (er) og';
