<?php

$_COS_LANG_MODULE['flood: You can post agian'] = 'Dann nichts wie los und macht wieder Beiträge';
$_COS_LANG_MODULE['flood: You should be able to post'] = 'Sie sollten in der Lage zu verfassen';
$_COS_LANG_MODULE['flood:: exceed time limit title'] = 'Nicht möglich, jetzt schreiben';
$_COS_LANG_MODULE['flood: Max Amount of posts is'] = 'Max Anzahl der Beiträge ist';
$_COS_LANG_MODULE['flood: per'] = 'pro';
$_COS_LANG_MODULE['flood: days and'] = 'Tag (e) und';
$_COS_LANG_MODULE['flood: hours and'] = 'h (n) und';
$_COS_LANG_MODULE['flood: minutes and'] = 'Minute (n) und';
$_COS_LANG_MODULE['flood: seconds'] = 'Sekunde (n)';
$_COS_LANG_MODULE['flood: Your post counter will be reset in'] = 'Die Nachricht wird in Zähler zurückgesetzt werden';
