<?php

$_COS_LANG_MODULE['flood: You should be able to post'] = 'Voit lähettää uudelleen';
$_COS_LANG_MODULE['flood: You can post agian'] = 'Vain palata ja lähettää uudelleen';
$_COS_LANG_MODULE['flood:: exceed time limit title'] = 'Et voi lähettää tällä hetkellä';
$_COS_LANG_MODULE['flood: Max Amount of posts is'] = 'Max ennätys on';
$_COS_LANG_MODULE['flood: per'] = 'kohti';
$_COS_LANG_MODULE['flood: Your post counter will be reset in'] = 'Voit lähettää uudelleen';
$_COS_LANG_MODULE['flood: minutes and'] = 'minuutti (a) ja';
$_COS_LANG_MODULE['flood: seconds'] = 'toinen (s)';
$_COS_LANG_MODULE['flood: days and'] = 'päivä (s) ja';
$_COS_LANG_MODULE['flood: hours and'] = 'tunti (a) ja';
