<?php

$_COS_LANG_MODULE['flood: You can post agian'] = 'Bara gå vidare och gör inlägg igen';
$_COS_LANG_MODULE['flood: You should be able to post'] = 'Du bör kunna posta';
$_COS_LANG_MODULE['flood:: exceed time limit title'] = 'Inte möjligt att posta just nu';
$_COS_LANG_MODULE['flood: Max Amount of posts is'] = 'Max Antal inlägg är';
$_COS_LANG_MODULE['flood: per'] = 'per';
$_COS_LANG_MODULE['flood: days and'] = 'dag (ar) och';
$_COS_LANG_MODULE['flood: hours and'] = 'timme (timmar) och';
$_COS_LANG_MODULE['flood: minutes and'] = 'minut (er) och';
$_COS_LANG_MODULE['flood: seconds'] = 'sekund (-er)';
$_COS_LANG_MODULE['flood: Your post counter will be reset in'] = 'Din post räknare återställs i';
